language: java
jdk:
  - openjdk8

sudo: required

services:
  - docker

script:
  - cd ../docker/dev
  - docker-compose up
  - cd ../../src
  - mvn test -P test-consumer
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)