dist: trusty
language: java
jdk:
  - oraclejdk8

before_script:
  - cd docker/dev
  - docker-compose up
  - docker ps
  - cd ../..

script:
  - mvn test

after_success:
  - mvn cobertura:cobertura
  - bash <(curl -s https://codecov.io/bash)