language: java
jdk:
  - openjdk8

sudo: required

services:
  - docker

before_install:
  - cd docker/dev
  - docker-compose up

before_script:
  - cd ../../src

script:
  - mvn test -Ptest-consumer
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)